sudo: required
dist: trusty
language: generic
env:
  global:
    - SINGULARITY_IMAGE=aspera-singularity.simg
    - VERSION=2.5.2
  matrix:
    - SPEC=Singularity
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libarchive-dev squashfs-tools wget
install:
  - wget https://github.com/sylabs/singularity/releases/download/$VERSION/singularity-$VERSION.tar.gz
  - tar xvf singularity-$VERSION.tar.gz
  - cd singularity-$VERSION
  - ./configure --prefix=/usr/local
  - make
  - sudo make install
before_script:
  - sudo singularity build $SINGULARITY_IMAGE $SPEC
  - chmod +x run_tests.sh
script: ./run_tests.sh
notifications:
  email:
    on_success: never
    on_failure: always
