sudo: required
dist: trusty
language: generic
env:
  global:
    - SINGULARITY_IMAGE=aspera-singularity.simg
  matrix:
    - SPEC=Singularity
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y squashfs-tools wget
install:
  - wget -O- http://neuro.debian.net/lists/stretch.de-m.libre | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - sudo apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
  - sudo apt-get update -qq
  - sudo apt-get install -y singularity-container
before_script:
  - sudo singularity build $SINGULARITY_IMAGE $SPEC
script: ./run_tests.sh
notifications:
  email:
    on_success: never
    on_failure: always
